#!/bin/bash

# DMENU scrupt

# Variables
TMP_DIR="/tmp"

cache="${TMP_DIR}/dmenu_cache"
history_file="$HOME/dmenu_hist"
running="${TMP_DIR}/dmenu_running"

if [[ ! -e ${history_file} ]] ; then
	touch "${history_file}"
fi


if [[ "/home/saro/.config/gtk-3.0/bookmarks" -nt $cache || ! -e /tmp/dmenu_cache  || \
	"/usr/share/applications" -nt $cache || "$HOME/.local/share/applications" -nt $cache ]]; then

	# Reset cache file
	echo "" > $cache
	grep -v '^ *#' < "/home/saro/.config/gtk-3.0/bookmarks" | while IFS= read -r i; do
		echo "${i##*/}_dir" >> $cache
	done;

	for i in ~/.local/share/applications/*.desktop; do
		grep "Name=" "$i" | head -n1 | sed 's/Name=//' >> $cache
	done

	for i in /usr/share/applications/*.desktop; do
		grep "Name=" "$i" | head -n1 | sed 's/Name=//' >> $cache
	done

	for i in /usr/local/share/applications/*.desktop; do
		grep "Name=" "$i" | head -n1 | sed 's/Name=//' >> $cache
	done
fi

cat "${history_file}" > $running
sed '/^$/d' $cache >> $running

result=$(dmenu-wl -b -i "$@" -fn 'Share Tech Mono-12'< $running)

err=0
desktopfile=""

if [[ $result != "" ]] ; then
	itsdir=".*_dir$"
	if [[ $result =~ $itsdir ]] ; then
		# echo " DIR: $(cat ~/.gtk-bookmarks| awk {'print $1'}|grep ".*/${result%_dir}$"| head -n1)"
		thunar "$(awk '{print $1}' /home/saro/.config/gtk-3.0/bookmarks |grep ".*/${result%_dir}$"| head -n1)"
	else
		desktopfile=$(grep -l "Name=${result}" ~/.local/share/applications/*.desktop)
		[[ -z ${desktopfile} ]] && desktopfile=$(grep -l "Name=${result}" /usr/share/applications/*.desktop)
		[[ -z ${desktopfile} ]] && desktopfile=$(grep -l "Name=${result}" /usr/local/share/applications/*.desktop)
		[[ -z ${desktopfile} ]] && err=1

		if [[ $err != "1" ]]; then
			ex=$(grep "Exec=" "$desktopfile"|sed 's/^.*Exec=//'|head -n1|sed 's/%.*//')
			echo "DESKTOP: $desktopfile  EXEC: $ex"
			sh -c "${ex}&"
		else
			echo "ERROR"
			exit 1
		fi
	fi

	if [[ $err -eq 0 ]]; then
		hist=$(cat "${history_file}")
		printf "%s\n%s" "${result}" "$hist" | awk '!x[$0]++' > "${history_file}"
	fi
fi

